version: '3.8'
services:
  amazon-auth-db:
    image: postgres:15
    container_name: amazon-auth-db-container
    restart: always
    environment:
      - POSTGRES_DB=${AMAZON_AUTH_PG_DB}
      - POSTGRES_USER=${AMAZON_AUTH_PG_USER}
      - POSTGRES_PASSWORD=${AMAZON_AUTH_PG_PASSWORD}
    env_file:
      - .env
    ports:
      - '${AMAZON_AUTH_PG_PORT}:5432'
    volumes:
      - amazon-auth-db-data:/var/lib/postgresql/data
    networks:
      - amazon-auth-network

  # amazon-auth-srv:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: amazon-auth-srv-container
  #   env_file:
  #     - .env
  #   ports:
  #     - '${AMAZON_AUTH_SRV_HTTP_PORT}:${AMAZON_AUTH_SRV_HTTP_PORT}'
  #   depends_on:
  #     - amazon-auth-db
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   networks:
  #     - amazon-auth-network

volumes:
  amazon-auth-db-data:

networks:
  amazon-auth-network:
    driver: bridge
